.MODEL SMALL
.STACK 100H
.DATA
     ;DECLARE VARIABLES HERE
     
.CODE
MAIN PROC
    ;INITIALYZING DS
    MOV AX,@DATA
    MOV DS,AX
    ;ENTER YOUR CODE HERE
    MOV BL, 2
    MOV CL, 3
    ;TAKING A TEMPORARY REGISTER TO STORE VALUE OF BL
    ADD DL, BL
    ;SWAPPING BL
    SUB BL, BL        
    ADD BL, CL
    ;SWAPPING CL
    SUB CL, CL
    ADD CL, DL 
    ;EXIT TO DOS
    MOV AX,4C00H
    INT 21H
    MAIN ENDP
END MAIN


