.MODEL SMALL
.STACK 100H
.DATA
    X DB 5
    Y DB 10
    Z DB 5     
.CODE
MAIN PROC
    ;INITIALYZING DS
    MOV AX,@DATA
    MOV DS,AX
    ;ENTER YOUR CODE HERE
    ;CALCULATING THE DENOMINATOR
    MOV AL, 4
    MOV BL, X
    MUL BL
    MOV BL, Z
    MUL BL        
    MOV BX, AX 
    ;CALCULATING THE NUMERATOR
    MOV AL, Y
    MOV CL, Y    
    MUL CL
    ;FINAL CALCULATION
    DIV BL
    ;EXIT TO DOS
    MOV AX,4C00H
    INT 21H
    MAIN ENDP
END MAIN


