.MODEL SMALL
.STACK 100H
.DATA
         
.CODE
MAIN PROC
    ;INITIALYZING DS
    MOV AX,@DATA
    MOV DS,AX
    ;ENTER YOUR CODE HERE
    
    ;TAKING THE INPUT
    MOV BX, 1
    MOV AX, BX
    
    ;STARTING THE LOOP  
    FIND_SUM:       
    ADD BX, 2
    SUB AX, BX
    ADD BX, 2
    
    ;KEEPING THE RESULT IN AX
    ADD AX, BX
    
    ;LOOPING UNTIL 505 IS REACHED
    CMP BX, 505
    JGE EXIT
    JMP FIND_SUM
    
    
    ;EXITING, THE VALUE OF AX REGISTER IS THE SUM
    EXIT:
    MAIN ENDP
END MAIN


