.MODEL SMALL
.STACK 100H
.DATA
     ;DECLARE VARIABLES HERE
     
     
.CODE
MAIN PROC
    ;INITIALYZING DS
    MOV AX,@DATA
    MOV DS,AX
    ;ENTER YOUR CODE HERE
    
    ;TAKING THE LOWERCASE LETTER AS INPUT
    MOV AH, 1
    INT 21H
    MOV BL, 20H
    SUB AL, BL
    MOV CL, AL
    
    ;JUMPING TO NEXT LINE
    MOV AH, 2
    MOV DL, 0DH
    INT 21H
    MOV DL, 0AH
    INT 21H
    
    ;PRINTING THE CORRESPONDING UPPERCASE LETTER
    MOV DL, CL
    MOV AH, 2
    INT 21H
    ;EXIT TO DOS
    MOV AX,4C00H
    INT 21H
    MAIN ENDP
END MAIN


