.MODEL SMALL
.STACK 100H
.DATA
    ;DECLARE VARIABLES HERE
    X DB "ENTER$"
    Y DB "A HEX DIGIT: $"
    Z DB "IN DECIMAL IT IS $"
     
.CODE
MAIN PROC
    ;INITIALYZING DS
    MOV AX,@DATA
    MOV DS,AX
    ;ENTER YOUR CODE HERE
    
    ;PRINTING THE FIRST MESSAGE
    LEA DX, X
    MOV AH, 9
    INT 21H
    
    ;JUMPING TO NEXT LINE
    MOV AH, 2
    MOV DL, 0DH
    INT 21H
    MOV DL, 0AH
    INT 21H
    
    ;PRINTING THE SECOND MESSAGE
    LEA DX, Y
    MOV AH, 9
    INT 21H
    
    ;TAKING A HEX DIGIT A-F AS INPUT
    MOV AH, 1
    INT 21H
    MOV BL, 11H 
    SUB AL, BL
    MOV BL, AL
    
    ;JUMPING TO NEXT LINE
    MOV AH, 2
    MOV DL, 0DH
    INT 21H
    MOV DL, 0AH
    INT 21H
    
    ;PRINTING THE THIRD MESSAGE
    LEA DX, Z
    MOV AH, 9
    INT 21H
    
    ;PRINTING THE FIRST DECIMAL NUMBER "1"
    MOV DL, 31H    
    MOV AH, 2
    INT 21H
    
    ;PRINTING THE SECOND DECIMAL NUMBER
    MOV DL, BL    
    MOV AH, 2
    INT 21H
    
    ;EXIT TO DOS
    MOV AX,4C00H
    INT 21H
    MAIN ENDP
END MAIN


